### ISSUE TITLE
Error on npm start, any idea?

### ISSUE THREAD

**Issue by neilyoung** [pujaagarwal5263/Mediasoup#1]
```
ubuntu@mediasoup:~/Mediasoup$ npm start

> mediasoup-custom@1.0.0 start /home/ubuntu/Mediasoup
> node src/app.js

/home/ubuntu/Mediasoup/src/app.js:51
(async () => {
^

TypeError: (intermediate value) is not a function
    at Object.<anonymous> (/home/ubuntu/Mediasoup/src/app.js:51:1)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup-custom@1.0.0 start: `node src/app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mediasoup-custom@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2023-03-28T12_32_53_555Z-debug.log
ubuntu@mediasoup:~/Mediasoup$ 

```

```
ubuntu@mediasoup:~/Mediasoup$ cat /home/ubuntu/.npm/_logs/2023-03-28T12_32_53_555Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.18
3 info using node@v16.19.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mediasoup-custom@1.0.0~prestart: mediasoup-custom@1.0.0
6 info lifecycle mediasoup-custom@1.0.0~start: mediasoup-custom@1.0.0
7 verbose lifecycle mediasoup-custom@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle mediasoup-custom@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/Mediasoup/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle mediasoup-custom@1.0.0~start: CWD: /home/ubuntu/Mediasoup
10 silly lifecycle mediasoup-custom@1.0.0~start: Args: [ '-c', 'node src/app.js' ]
11 silly lifecycle mediasoup-custom@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle mediasoup-custom@1.0.0~start: Failed to exec start script
13 verbose stack Error: mediasoup-custom@1.0.0 start: `node src/app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (node:events:513:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (node:events:513:28)
13 verbose stack     at maybeClose (node:internal/child_process:1100:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
14 verbose pkgid mediasoup-custom@1.0.0
15 verbose cwd /home/ubuntu/Mediasoup
16 verbose Linux 5.4.0-146-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v16.19.1
19 verbose npm  v6.14.18
20 error code ELIFECYCLE
21 error errno 1
22 error mediasoup-custom@1.0.0 start: `node src/app.js`
22 error Exit status 1
23 error Failed at the mediasoup-custom@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
ubuntu@mediasoup:~/Mediasoup$ 

```

**Comment by neilyoung** [comment]
Removed the async construct. Anyway, not the only bug.

RoomClient.js:409 Produce error: DOMException: Failed to execute 'addTransceiver' on 'RTCPeerConnection': Attempted to set RtpParameters scalabilityMode to an unsupported value for the current codecs.

Disregard please.

**Comment by neilyoung** [comment]
https://mediasoup.discourse.group/t/failed-to-execute-addtransceiver-on-rtcpeerconnection/4827

Fixed it

**Comment by pujaagarwal5263** [comment]
Thank you
*Regards,*
*Puja Agarwal*
